
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the WijmoGridTestData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.WijmoGridTestDataService WijmoGridTestData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.WijmoGridTestData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.WijmoGridTestData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WijmoGridTestDataService> WijmoGridTestData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.WijmoGridTestData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WijmoGridTestDataService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WijmoGridTestDataService>.Entry
                    WijmoGridTestData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WijmoGridTestDataService>.Entry(
                        "WijmoGridTestData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._WijmoGridTestData_Stub);
                private static void _WijmoGridTestData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WijmoGridTestDataService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._WijmoGridTestData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.WijmoGridTestDataService>.Data _WijmoGridTestData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the WijmoGridTestData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class WijmoGridTestData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public WijmoGridTestData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the SalesOrderDetails entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SalesOrderDetail> SalesOrderDetails
        {
            get
            {
                return global::LightSwitchApplication.WijmoGridTestData.DetailsClass.GetValue(this, global::LightSwitchApplication.WijmoGridTestData.DetailsClass.PropertySetProperties.SalesOrderDetails);
            }
        }
        
        /// <summary>
        /// Gets the SalesOrderHeaders entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.SalesOrderHeader> SalesOrderHeaders
        {
            get
            {
                return global::LightSwitchApplication.WijmoGridTestData.DetailsClass.GetValue(this, global::LightSwitchApplication.WijmoGridTestData.DetailsClass.PropertySetProperties.SalesOrderHeaders);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="SalesOrderDetailID">
        /// The value of the 'SalesOrderDetailID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.SalesOrderDetail SalesOrderDetails_Single(global::System.Nullable<int> SalesOrderDetailID)
        {
            return this.Details.Methods.SalesOrderDetails_Single.CreateInvocation(SalesOrderDetailID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="SalesOrderDetailID">
        /// The value of the 'SalesOrderDetailID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.SalesOrderDetail SalesOrderDetails_SingleOrDefault(global::System.Nullable<int> SalesOrderDetailID)
        {
            return this.Details.Methods.SalesOrderDetails_SingleOrDefault.CreateInvocation(SalesOrderDetailID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="SalesOrderID">
        /// The value of the 'SalesOrderID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.SalesOrderHeader SalesOrderHeaders_Single(global::System.Nullable<int> SalesOrderID)
        {
            return this.Details.Methods.SalesOrderHeaders_Single.CreateInvocation(SalesOrderID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="SalesOrderID">
        /// The value of the 'SalesOrderID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.SalesOrderHeader SalesOrderHeaders_SingleOrDefault(global::System.Nullable<int> SalesOrderID)
        {
            return this.Details.Methods.SalesOrderHeaders_SingleOrDefault.CreateInvocation(SalesOrderID).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.WijmoGridTestData.DetailsClass.PropertySet, global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSetProperties.SalesOrderDetails_Single;
                var initializePropertyEntry = global::LightSwitchApplication.WijmoGridTestData.DetailsClass.PropertySetProperties.SalesOrderDetails;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.WijmoGridTestData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail> SalesOrderDetails_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSetProperties.SalesOrderDetails_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail> SalesOrderDetails_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSetProperties.SalesOrderDetails_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader> SalesOrderHeaders_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSetProperties.SalesOrderHeaders_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader> SalesOrderHeaders_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSetProperties.SalesOrderHeaders_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail> SalesOrderDetails
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WijmoGridTestData.DetailsClass.PropertySetProperties.SalesOrderDetails) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader> SalesOrderHeaders
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.WijmoGridTestData.DetailsClass.PropertySetProperties.SalesOrderHeaders) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Entry
                    SalesOrderDetails_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Entry(
                        "SalesOrderDetails_Single",
                        global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSetProperties._SalesOrderDetails_Single_Stub);
                private static void _SalesOrderDetails_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Data> c, global::LightSwitchApplication.WijmoGridTestData.DetailsClass d, object sf)
                {
                    c(d, ref d._SalesOrderDetails_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Entry
                    SalesOrderDetails_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Entry(
                        "SalesOrderDetails_SingleOrDefault",
                        global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSetProperties._SalesOrderDetails_SingleOrDefault_Stub);
                private static void _SalesOrderDetails_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Data> c, global::LightSwitchApplication.WijmoGridTestData.DetailsClass d, object sf)
                {
                    c(d, ref d._SalesOrderDetails_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Entry
                    SalesOrderHeaders_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Entry(
                        "SalesOrderHeaders_Single",
                        global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSetProperties._SalesOrderHeaders_Single_Stub);
                private static void _SalesOrderHeaders_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Data> c, global::LightSwitchApplication.WijmoGridTestData.DetailsClass d, object sf)
                {
                    c(d, ref d._SalesOrderHeaders_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Entry
                    SalesOrderHeaders_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Entry(
                        "SalesOrderHeaders_SingleOrDefault",
                        global::LightSwitchApplication.WijmoGridTestData.DetailsClass.MethodSetProperties._SalesOrderHeaders_SingleOrDefault_Stub);
                private static void _SalesOrderHeaders_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Data> c, global::LightSwitchApplication.WijmoGridTestData.DetailsClass d, object sf)
                {
                    c(d, ref d._SalesOrderHeaders_SingleOrDefault, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Entry
                    SalesOrderDetails = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Entry(
                        "SalesOrderDetails",
                        global::LightSwitchApplication.WijmoGridTestData.DetailsClass.PropertySetProperties._SalesOrderDetails_Stub);
                private static void _SalesOrderDetails_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Data> c, global::LightSwitchApplication.WijmoGridTestData.DetailsClass d, object sf)
                {
                    c(d, ref d._SalesOrderDetails, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Entry
                    SalesOrderHeaders = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Entry(
                        "SalesOrderHeaders",
                        global::LightSwitchApplication.WijmoGridTestData.DetailsClass.PropertySetProperties._SalesOrderHeaders_Stub);
                private static void _SalesOrderHeaders_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Data> c, global::LightSwitchApplication.WijmoGridTestData.DetailsClass d, object sf)
                {
                    c(d, ref d._SalesOrderHeaders, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Data _SalesOrderDetails;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Data _SalesOrderHeaders;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Data _SalesOrderDetails_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderDetail>.Data _SalesOrderDetails_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Data _SalesOrderHeaders_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.WijmoGridTestData, global::LightSwitchApplication.WijmoGridTestData.DetailsClass, global::LightSwitchApplication.SalesOrderHeader>.Data _SalesOrderHeaders_SingleOrDefault;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
