//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the WijmoGridTestData datasource.
    /// </summary>
    public sealed partial class WijmoGridTestDataService
        : global::LightSwitchApplication.WijmoGridTestData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public WijmoGridTestDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_Inserting(global::LightSwitchApplication.SalesOrderDetail entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_Inserted(global::LightSwitchApplication.SalesOrderDetail entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_Updating(global::LightSwitchApplication.SalesOrderDetail entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_Updated(global::LightSwitchApplication.SalesOrderDetail entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_Deleting(global::LightSwitchApplication.SalesOrderDetail entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_Deleted(global::LightSwitchApplication.SalesOrderDetail entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_Validate(global::LightSwitchApplication.SalesOrderDetail entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderDetails_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SalesOrderDetail, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_Inserting(global::LightSwitchApplication.SalesOrderHeader entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_Inserted(global::LightSwitchApplication.SalesOrderHeader entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_Updating(global::LightSwitchApplication.SalesOrderHeader entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_Updated(global::LightSwitchApplication.SalesOrderHeader entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_Deleting(global::LightSwitchApplication.SalesOrderHeader entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_Deleted(global::LightSwitchApplication.SalesOrderHeader entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_Validate(global::LightSwitchApplication.SalesOrderHeader entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SalesOrderHeaders_Filter(ref global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SalesOrderHeader, bool>> filter);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executing(global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Executed(global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_ExecuteFailed(global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.WijmoGridTestDataService, global::LightSwitchApplication.SalesOrderDetail>
                __SalesOrderDetailsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.WijmoGridTestDataService, global::LightSwitchApplication.SalesOrderDetail>(
                    "SalesOrderDetails",
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_CanInsert,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_CanUpdate,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_CanDelete,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_CanRead,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_Inserting,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_Inserted,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_Updating,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_Updated,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_Deleting,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_Deleted,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_Validate,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderDetails_Filter);
            private static bool __SalesOrderDetails_CanInsert(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                bool result = true;
                d.SalesOrderDetails_CanInsert(ref result);
                return result;
            }
            private static bool __SalesOrderDetails_CanUpdate(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                bool result = true;
                d.SalesOrderDetails_CanUpdate(ref result);
                return result;
            }
            private static bool __SalesOrderDetails_CanDelete(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                bool result = true;
                d.SalesOrderDetails_CanDelete(ref result);
                return result;
            }
            private static bool __SalesOrderDetails_CanRead(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                bool result = true;
                d.SalesOrderDetails_CanRead(ref result);
                return result;
            }
            private static void __SalesOrderDetails_Inserting(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderDetail e)
            {
                d.SalesOrderDetails_Inserting(e);
            }
            private static void __SalesOrderDetails_Inserted(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderDetail e)
            {
                d.SalesOrderDetails_Inserted(e);
            }
            private static void __SalesOrderDetails_Updating(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderDetail e)
            {
                d.SalesOrderDetails_Updating(e);
            }
            private static void __SalesOrderDetails_Updated(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderDetail e)
            {
                d.SalesOrderDetails_Updated(e);
            }
            private static void __SalesOrderDetails_Deleting(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderDetail e)
            {
                d.SalesOrderDetails_Deleting(e);
            }
            private static void __SalesOrderDetails_Deleted(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderDetail e)
            {
                d.SalesOrderDetails_Deleted(e);
            }
            private static void __SalesOrderDetails_Validate(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderDetail e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.SalesOrderDetails_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SalesOrderDetail, bool>> __SalesOrderDetails_Filter(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SalesOrderDetail, bool>> filter = null;
                d.SalesOrderDetails_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.WijmoGridTestDataService, global::LightSwitchApplication.SalesOrderHeader>
                __SalesOrderHeadersEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.WijmoGridTestDataService, global::LightSwitchApplication.SalesOrderHeader>(
                    "SalesOrderHeaders",
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_CanInsert,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_CanUpdate,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_CanDelete,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_CanRead,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_Inserting,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_Inserted,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_Updating,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_Updated,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_Deleting,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_Deleted,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_Validate,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SalesOrderHeaders_Filter);
            private static bool __SalesOrderHeaders_CanInsert(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                bool result = true;
                d.SalesOrderHeaders_CanInsert(ref result);
                return result;
            }
            private static bool __SalesOrderHeaders_CanUpdate(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                bool result = true;
                d.SalesOrderHeaders_CanUpdate(ref result);
                return result;
            }
            private static bool __SalesOrderHeaders_CanDelete(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                bool result = true;
                d.SalesOrderHeaders_CanDelete(ref result);
                return result;
            }
            private static bool __SalesOrderHeaders_CanRead(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                bool result = true;
                d.SalesOrderHeaders_CanRead(ref result);
                return result;
            }
            private static void __SalesOrderHeaders_Inserting(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderHeader e)
            {
                d.SalesOrderHeaders_Inserting(e);
            }
            private static void __SalesOrderHeaders_Inserted(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderHeader e)
            {
                d.SalesOrderHeaders_Inserted(e);
            }
            private static void __SalesOrderHeaders_Updating(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderHeader e)
            {
                d.SalesOrderHeaders_Updating(e);
            }
            private static void __SalesOrderHeaders_Updated(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderHeader e)
            {
                d.SalesOrderHeaders_Updated(e);
            }
            private static void __SalesOrderHeaders_Deleting(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderHeader e)
            {
                d.SalesOrderHeaders_Deleting(e);
            }
            private static void __SalesOrderHeaders_Deleted(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderHeader e)
            {
                d.SalesOrderHeaders_Deleted(e);
            }
            private static void __SalesOrderHeaders_Validate(global::LightSwitchApplication.WijmoGridTestDataService d, global::LightSwitchApplication.SalesOrderHeader e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.SalesOrderHeaders_Validate(e, r);
            }
            private static global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SalesOrderHeader, bool>> __SalesOrderHeaders_Filter(global::LightSwitchApplication.WijmoGridTestDataService d)
            {
                global::System.Linq.Expressions.Expression<global::System.Func<global::LightSwitchApplication.SalesOrderHeader, bool>> filter = null;
                d.SalesOrderHeaders_Filter(ref filter);
                return filter;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.WijmoGridTestDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.WijmoGridTestDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.WijmoGridTestDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.WijmoGridTestDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.WijmoGridTestDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.WijmoGridTestDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.WijmoGridTestDataService>
                ___QueryEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryEntry<global::LightSwitchApplication.WijmoGridTestDataService>(
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__Query_Executing,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__Query_Executed,
                    global::LightSwitchApplication.WijmoGridTestDataService.DetailsClass.__Query_Failed);
            private static void __Query_Executing(global::LightSwitchApplication.WijmoGridTestDataService d, global::Microsoft.LightSwitch.QueryExecutingDescriptor queryDescriptor)
            {
                d.Query_Executing(queryDescriptor);
            }
            private static void __Query_Executed(global::LightSwitchApplication.WijmoGridTestDataService d, global::Microsoft.LightSwitch.QueryExecutedDescriptor queryDescriptor)
            {
                d.Query_Executed(queryDescriptor);
            }
            private static void __Query_Failed(global::LightSwitchApplication.WijmoGridTestDataService d, global::Microsoft.LightSwitch.QueryExecuteFailedDescriptor queryDescriptor)
            {
                d.Query_ExecuteFailed(queryDescriptor);
            }
        }
    
        #endregion
    }
    
    #endregion
}
