//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class TimeSheets_Dev_LeoDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.TimeSheets_Dev_Leo>
    {
    
        public TimeSheets_Dev_LeoDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).TimeSheets_Dev_Leo;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class TimeSheets_Dev_LeoServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.TimeSheets_Dev_Leo>
    {
        public TimeSheets_Dev_LeoServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Timesheet> TimesheetsByDate(global::System.Nullable<global::System.DateTime> StartDate, global::System.Nullable<global::System.DateTime> EndDate, string TimesheetPerson)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Timesheet> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.Timesheet>("Timesheets"),
                (t) => ((((StartDate.HasValue == false) || (StartDate.HasValue && (t.DimDate.c_Date >= StartDate))) && ((EndDate.HasValue == false) || (EndDate.HasValue && (t.DimDate.c_Date <= EndDate)))) && ((TimesheetPerson == null) || t.TimesheetPerson.Contains(TimesheetPerson))));
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Person> PersonSorted()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Person> query;
            query = global::System.Linq.Queryable.OrderBy(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::LightSwitchApplication.Implementation.Person>("People"),
                    (p) => (p.ActiveType.ID == 1)),
                (p) => p.PersonName);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DimDate> BillingDate()
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.DimDate> query;
            global::System.DateTime endOfYear1 = global::Microsoft.LightSwitch.RelativeDates.EndOfYear();
            query = global::System.Linq.Queryable.OrderByDescending(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::LightSwitchApplication.Implementation.DimDate>("DimDates"),
                    (d) => ((d.c_Date <= endOfYear1) && (d.c_Date >= new global::System.DateTime(2010, 3, 1, 0, 0, 0, 0, System.DateTimeKind.Unspecified)))),
                (d) => d.c_Date);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Client> FilteredClient(string ClientName)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Client> query;
            query = global::System.Linq.Queryable.OrderBy(
                global::System.Linq.Queryable.Where(
                    this.GetQuery<global::LightSwitchApplication.Implementation.Client>("Clients"),
                    (c) => (((ClientName == null) || c.ClientName.Contains(ClientName)) && (c.ActiveType.ID == 1))),
                (c) => c.ClientName);
            return query;
        }
    
        public global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Project> ProjectsFilter(string ClientName, string ProjectName)
        {
            global::System.Linq.IQueryable<global::LightSwitchApplication.Implementation.Project> query;
            query = global::System.Linq.Queryable.Where(
                this.GetQuery<global::LightSwitchApplication.Implementation.Project>("Projects"),
                (p) => (((((ClientName == null) || p.Client.ClientName.Contains(ClientName)) && ((ProjectName == null) || p.ProjectName.Contains(ProjectName))) && (p.ActiveType.ID == 1)) && (p.Client.ActiveType.ID == 1)));
            return query;
        }
    
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.BillingDetail))
            {
                return new global::LightSwitchApplication.Implementation.BillingDetail();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.BillingStatus))
            {
                return new global::LightSwitchApplication.Implementation.BillingStatus();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Client))
            {
                return new global::LightSwitchApplication.Implementation.Client();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.DimDate))
            {
                return new global::LightSwitchApplication.Implementation.DimDate();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Person))
            {
                return new global::LightSwitchApplication.Implementation.Person();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Timesheet))
            {
                return new global::LightSwitchApplication.Implementation.Timesheet();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TimesheetDetail))
            {
                return new global::LightSwitchApplication.Implementation.TimesheetDetail();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TypeOfWork))
            {
                return new global::LightSwitchApplication.Implementation.TypeOfWork();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.RoleType))
            {
                return new global::LightSwitchApplication.Implementation.RoleType();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ClientRole))
            {
                return new global::LightSwitchApplication.Implementation.ClientRole();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.SystemRole))
            {
                return new global::LightSwitchApplication.Implementation.SystemRole();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.ActiveType))
            {
                return new global::LightSwitchApplication.Implementation.ActiveType();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.TimeSheets_Dev_Leo CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.TimeSheets_Dev_Leo(this.GetEntityConnectionString(
                "TimeSheets_Dev_Leo",
                "res://" + assemblyName + "/TimeSheets_Dev_Leo.csdl|res://" + assemblyName + "/TimeSheets_Dev_Leo.ssdl|res://" + assemblyName + "/TimeSheets_Dev_Leo.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.BillingDetail))
            {
                return new global::LightSwitchApplication.Implementation.BillingDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.BillingStatus))
            {
                return new global::LightSwitchApplication.Implementation.BillingStatus();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Client))
            {
                return new global::LightSwitchApplication.Implementation.Client();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.DimDate))
            {
                return new global::LightSwitchApplication.Implementation.DimDate();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Person))
            {
                return new global::LightSwitchApplication.Implementation.Person();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Project))
            {
                return new global::LightSwitchApplication.Implementation.Project();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Timesheet))
            {
                return new global::LightSwitchApplication.Implementation.Timesheet();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TimesheetDetail))
            {
                return new global::LightSwitchApplication.Implementation.TimesheetDetail();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TypeOfWork))
            {
                return new global::LightSwitchApplication.Implementation.TypeOfWork();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RoleType))
            {
                return new global::LightSwitchApplication.Implementation.RoleType();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ClientRole))
            {
                return new global::LightSwitchApplication.Implementation.ClientRole();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.SystemRole))
            {
                return new global::LightSwitchApplication.Implementation.SystemRole();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.ActiveType))
            {
                return new global::LightSwitchApplication.Implementation.ActiveType();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.TimeSheets_Dev_LeoService))
            {
                return new global::LightSwitchApplication.TimeSheets_Dev_LeoService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.TimeSheets_Dev_LeoService))
            {
                return new global::LightSwitchApplication.Implementation.TimeSheets_Dev_LeoServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.BillingDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.BillingDetail);
            }
            if (typeof(global::LightSwitchApplication.BillingStatus) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.BillingStatus);
            }
            if (typeof(global::LightSwitchApplication.Client) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Client);
            }
            if (typeof(global::LightSwitchApplication.DimDate) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.DimDate);
            }
            if (typeof(global::LightSwitchApplication.Person) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Person);
            }
            if (typeof(global::LightSwitchApplication.Project) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Project);
            }
            if (typeof(global::LightSwitchApplication.Timesheet) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Timesheet);
            }
            if (typeof(global::LightSwitchApplication.TimesheetDetail) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TimesheetDetail);
            }
            if (typeof(global::LightSwitchApplication.TypeOfWork) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TypeOfWork);
            }
            if (typeof(global::LightSwitchApplication.RoleType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RoleType);
            }
            if (typeof(global::LightSwitchApplication.ClientRole) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ClientRole);
            }
            if (typeof(global::LightSwitchApplication.SystemRole) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.SystemRole);
            }
            if (typeof(global::LightSwitchApplication.ActiveType) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.ActiveType);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class BillingDetail :
        global::LightSwitchApplication.BillingDetail.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.BillingDetail.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Client");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.BillingDetail.DetailsClass.IImplementation.Person
        {
            get
            {
                return this.Person;
            }
            set
            {
                this.Person = (global::LightSwitchApplication.Implementation.Person)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Person");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.BillingDetail.DetailsClass.IImplementation.ClientRole
        {
            get
            {
                return this.ClientRole;
            }
            set
            {
                this.ClientRole = (global::LightSwitchApplication.Implementation.ClientRole)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ClientRole");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.BillingDetail.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.BillingDetail.DetailsClass.IImplementation.DimDate
        {
            get
            {
                return this.DimDate;
            }
            set
            {
                this.DimDate = (global::LightSwitchApplication.Implementation.DimDate)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DimDate");
                }
            }
        }
        
        partial void OnBillingDetailClientIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Client");
            }
        }
        
        partial void OnBillingDetailPersonIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Person");
            }
        }
        
        partial void OnBillingDetailClientRoleIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ClientRole");
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        partial void OnBillingDetailDateIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DimDate");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class BillingStatus :
        global::LightSwitchApplication.BillingStatus.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.BillingStatus.DetailsClass.IImplementation.Projects
        {
            get
            {
                return this.Projects;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.BillingStatus.DetailsClass.IImplementation.TimesheetDetails
        {
            get
            {
                return this.TimesheetDetails;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.BillingStatus.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Client :
        global::LightSwitchApplication.Client.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.BillingDetails
        {
            get
            {
                return this.BillingDetails;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Client.DetailsClass.IImplementation.Projects
        {
            get
            {
                return this.Projects;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Client.DetailsClass.IImplementation.Person
        {
            get
            {
                return this.Person;
            }
            set
            {
                this.Person = (global::LightSwitchApplication.Implementation.Person)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Person");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Client.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnAccountManagerPersonIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Person");
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class DimDate :
        global::LightSwitchApplication.DimDate.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.DimDate.DetailsClass.IImplementation.TimesheetDetails
        {
            get
            {
                return this.TimesheetDetails;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DimDate.DetailsClass.IImplementation.Timesheets
        {
            get
            {
                return this.Timesheets;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.DimDate.DetailsClass.IImplementation.BillingDetails
        {
            get
            {
                return this.BillingDetails;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Person :
        global::LightSwitchApplication.Person.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Person.DetailsClass.IImplementation.BillingDetails
        {
            get
            {
                return this.BillingDetails;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Person.DetailsClass.IImplementation.Projects
        {
            get
            {
                return this.Projects;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Person.DetailsClass.IImplementation.TimesheetDetails
        {
            get
            {
                return this.TimesheetDetails;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Person.DetailsClass.IImplementation.SystemRole
        {
            get
            {
                return this.SystemRole;
            }
            set
            {
                this.SystemRole = (global::LightSwitchApplication.Implementation.SystemRole)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("SystemRole");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Person.DetailsClass.IImplementation.Clients
        {
            get
            {
                return this.Clients;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Person.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnPersonSystemRoleIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("SystemRole");
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Project :
        global::LightSwitchApplication.Project.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Project.DetailsClass.IImplementation.BillingStatus
        {
            get
            {
                return this.BillingStatus;
            }
            set
            {
                this.BillingStatus = (global::LightSwitchApplication.Implementation.BillingStatus)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("BillingStatus");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Project.DetailsClass.IImplementation.Client
        {
            get
            {
                return this.Client;
            }
            set
            {
                this.Client = (global::LightSwitchApplication.Implementation.Client)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Client");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Project.DetailsClass.IImplementation.Person
        {
            get
            {
                return this.Person;
            }
            set
            {
                this.Person = (global::LightSwitchApplication.Implementation.Person)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Person");
                }
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Project.DetailsClass.IImplementation.TimesheetDetails
        {
            get
            {
                return this.TimesheetDetails;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Project.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnBillableChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("BillingStatus");
            }
        }
        
        partial void OnClientIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Client");
            }
        }
        
        partial void OnAccountManagerPersonIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Person");
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Timesheet :
        global::LightSwitchApplication.Timesheet.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Timesheet.DetailsClass.IImplementation.TimesheetDetails
        {
            get
            {
                return this.TimesheetDetails;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Timesheet.DetailsClass.IImplementation.DimDate
        {
            get
            {
                return this.DimDate;
            }
            set
            {
                this.DimDate = (global::LightSwitchApplication.Implementation.DimDate)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DimDate");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Timesheet.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnTimesheetDateIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DimDate");
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TimesheetDetail :
        global::LightSwitchApplication.TimesheetDetail.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TimesheetDetail.DetailsClass.IImplementation.DimDate
        {
            get
            {
                return this.DimDate;
            }
            set
            {
                this.DimDate = (global::LightSwitchApplication.Implementation.DimDate)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DimDate");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TimesheetDetail.DetailsClass.IImplementation.Person
        {
            get
            {
                return this.Person;
            }
            set
            {
                this.Person = (global::LightSwitchApplication.Implementation.Person)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Person");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TimesheetDetail.DetailsClass.IImplementation.Project
        {
            get
            {
                return this.Project;
            }
            set
            {
                this.Project = (global::LightSwitchApplication.Implementation.Project)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Project");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TimesheetDetail.DetailsClass.IImplementation.Timesheet
        {
            get
            {
                return this.Timesheet;
            }
            set
            {
                this.Timesheet = (global::LightSwitchApplication.Implementation.Timesheet)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Timesheet");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TimesheetDetail.DetailsClass.IImplementation.TypeOfWork
        {
            get
            {
                return this.TypeOfWork;
            }
            set
            {
                this.TypeOfWork = (global::LightSwitchApplication.Implementation.TypeOfWork)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TypeOfWork");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TimesheetDetail.DetailsClass.IImplementation.BillingStatus
        {
            get
            {
                return this.BillingStatus;
            }
            set
            {
                this.BillingStatus = (global::LightSwitchApplication.Implementation.BillingStatus)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("BillingStatus");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TimesheetDetail.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnTimesheetDetailDateIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DimDate");
            }
        }
        
        partial void OnTimesheetDetailPersonIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Person");
            }
        }
        
        partial void OnTimesheetDetailProjectIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Project");
            }
        }
        
        partial void OnTimesheetIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Timesheet");
            }
        }
        
        partial void OnTimesheetTypeOfWorkIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TypeOfWork");
            }
        }
        
        partial void OnBillableChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("BillingStatus");
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TypeOfWork :
        global::LightSwitchApplication.TypeOfWork.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.TypeOfWork.DetailsClass.IImplementation.TimesheetDetails
        {
            get
            {
                return this.TimesheetDetails;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TypeOfWork.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RoleType :
        global::LightSwitchApplication.RoleType.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RoleType.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ClientRole :
        global::LightSwitchApplication.ClientRole.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ClientRole.DetailsClass.IImplementation.BillingDetails
        {
            get
            {
                return this.BillingDetails;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.ClientRole.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class SystemRole :
        global::LightSwitchApplication.SystemRole.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.SystemRole.DetailsClass.IImplementation.People
        {
            get
            {
                return this.People;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.SystemRole.DetailsClass.IImplementation.ActiveType
        {
            get
            {
                return this.ActiveType;
            }
            set
            {
                this.ActiveType = (global::LightSwitchApplication.Implementation.ActiveType)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("ActiveType");
                }
            }
        }
        
        partial void OnActiveChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("ActiveType");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class ActiveType :
        global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.BillingDetails
        {
            get
            {
                return this.BillingDetails;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.BillingStatus
        {
            get
            {
                return this.BillingStatus;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.Clients
        {
            get
            {
                return this.Clients;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.ClientRoles
        {
            get
            {
                return this.ClientRoles;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.People
        {
            get
            {
                return this.People;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.Projects
        {
            get
            {
                return this.Projects;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.RoleTypes
        {
            get
            {
                return this.RoleTypes;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.SystemRoles
        {
            get
            {
                return this.SystemRoles;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.Timesheets
        {
            get
            {
                return this.Timesheets;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.TimesheetDetails
        {
            get
            {
                return this.TimesheetDetails;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.ActiveType.DetailsClass.IImplementation.TypeOfWorks
        {
            get
            {
                return this.TypeOfWorks;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

