

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class ClientRole : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ClientRole entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ClientRole()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ClientRole(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ClientRole> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ClientRole.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRole_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRole_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ClientRoleName
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleName);
            }
            set
            {
                global::LightSwitchApplication.ClientRole.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ClientRoleID
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ClientRoleSourceKey
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleSourceKey);
            }
            set
            {
                global::LightSwitchApplication.ClientRole.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleSourceKey, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleSourceKey_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleSourceKey_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleSourceKey_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LoadDate
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.LoadDate);
            }
            set
            {
                global::LightSwitchApplication.ClientRole.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.LoadDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoadDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoadDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoadDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ClientRoleCode
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleCode);
            }
            set
            {
                global::LightSwitchApplication.ClientRole.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleCode, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleCode_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleCode_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ClientRoleCode_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> LoadDateID
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.LoadDateID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoadDateID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoadDateID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LoadDateID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime sys_CreatedOn
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_CreatedOn);
            }
            set
            {
                global::LightSwitchApplication.ClientRole.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_CreatedOn, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_CreatedOn_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_CreatedOn_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_CreatedOn_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string sys_CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.ClientRole.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime sys_ModifiedOn
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_ModifiedOn);
            }
            set
            {
                global::LightSwitchApplication.ClientRole.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_ModifiedOn, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_ModifiedOn_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_ModifiedOn_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_ModifiedOn_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string sys_ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_ModifiedBy);
            }
            set
            {
                global::LightSwitchApplication.ClientRole.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_ModifiedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void sys_ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.BillingDetail> BillingDetails
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.BillingDetails);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.BillingDetail> BillingDetailsQuery
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetQuery(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.BillingDetails);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.ActiveType ActiveType
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ActiveType);
            }
            set
            {
                global::LightSwitchApplication.ClientRole.DetailsClass.SetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ActiveType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActiveType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActiveType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActiveType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.InvoiceLine> InvoiceLines
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetValue(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.InvoiceLines);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.InvoiceLine> InvoiceLinesQuery
        {
            get
            {
                return global::LightSwitchApplication.ClientRole.DetailsClass.GetQuery(this, global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.InvoiceLines);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ClientRole,
                global::LightSwitchApplication.ClientRole.DetailsClass,
                global::LightSwitchApplication.ClientRole.DetailsClass.IImplementation,
                global::LightSwitchApplication.ClientRole.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleName;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass>.Entry
                __ClientRoleEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass>.Entry(
                    global::LightSwitchApplication.ClientRole.DetailsClass.__ClientRole_CreateNew,
                    global::LightSwitchApplication.ClientRole.DetailsClass.__ClientRole_Created,
                    global::LightSwitchApplication.ClientRole.DetailsClass.__ClientRole_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ClientRole __ClientRole_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ClientRole> es)
            {
                return new global::LightSwitchApplication.ClientRole(es);
            }
            private static void __ClientRole_Created(global::LightSwitchApplication.ClientRole e)
            {
                e.ClientRole_Created();
            }
            private static bool __ClientRole_AllowSaveWithErrors(global::LightSwitchApplication.ClientRole e)
            {
                bool result = false;
                e.ClientRole_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ClientRole.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string> ClientRoleName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, int> ClientRoleID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string> ClientRoleSourceKey
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleSourceKey) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime> LoadDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.LoadDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string> ClientRoleCode
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ClientRoleCode) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.Nullable<int>> LoadDateID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.LoadDateID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime> sys_CreatedOn
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_CreatedOn) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string> sys_CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime> sys_ModifiedOn
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_ModifiedOn) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string> sys_ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.sys_ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.BillingDetail> BillingDetails
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.BillingDetails) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.BillingDetail>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.ActiveType> ActiveType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ActiveType) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.ActiveType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.InvoiceLine> InvoiceLines
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.InvoiceLines) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.InvoiceLine>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string ClientRoleName { get; set; }
                new int ClientRoleID { get; }
                new string ClientRoleSourceKey { get; set; }
                new global::System.DateTime LoadDate { get; set; }
                new string ClientRoleCode { get; set; }
                new global::System.Nullable<int> LoadDateID { get; }
                new global::System.DateTime sys_CreatedOn { get; set; }
                new string sys_CreatedBy { get; set; }
                new global::System.DateTime sys_ModifiedOn { get; set; }
                new string sys_ModifiedBy { get; set; }
                new global::System.Collections.IEnumerable BillingDetails { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ActiveType { get; set; }
                new global::System.Collections.IEnumerable InvoiceLines { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry
                    ClientRoleName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry(
                        "ClientRoleName",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleName_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleName_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleName_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleName_GetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleName_SetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleName_OnValueChanged);
                private static void _ClientRoleName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._ClientRoleName, sf);
                }
                private static bool _ClientRoleName_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.ClientRoleName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ClientRoleName_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ClientRoleName_Validate(r);
                }
                private static string _ClientRoleName_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.ClientRoleName;
                }
                private static void _ClientRoleName_SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ClientRoleName = v;
                }
                private static void _ClientRoleName_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.ClientRoleName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, int>.Entry
                    ClientRoleID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, int>.Entry(
                        "ClientRoleID",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleID_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleID_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleID_OnValueChanged);
                private static void _ClientRoleID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, int>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._ClientRoleID, sf);
                }
                private static bool _ClientRoleID_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.ClientRoleID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ClientRoleID_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ClientRoleID_Validate(r);
                }
                private static int _ClientRoleID_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.ClientRoleID;
                }
                private static void _ClientRoleID_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.ClientRoleID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry
                    ClientRoleSourceKey = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry(
                        "ClientRoleSourceKey",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleSourceKey_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleSourceKey_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleSourceKey_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleSourceKey_GetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleSourceKey_SetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleSourceKey_OnValueChanged);
                private static void _ClientRoleSourceKey_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._ClientRoleSourceKey, sf);
                }
                private static bool _ClientRoleSourceKey_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.ClientRoleSourceKey_IsReadOnly(ref result);
                    return result;
                }
                private static void _ClientRoleSourceKey_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ClientRoleSourceKey_Validate(r);
                }
                private static string _ClientRoleSourceKey_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.ClientRoleSourceKey;
                }
                private static void _ClientRoleSourceKey_SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ClientRoleSourceKey = v;
                }
                private static void _ClientRoleSourceKey_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.ClientRoleSourceKey_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Entry
                    LoadDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Entry(
                        "LoadDate",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDate_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDate_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDate_GetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDate_SetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDate_OnValueChanged);
                private static void _LoadDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._LoadDate, sf);
                }
                private static bool _LoadDate_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.LoadDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _LoadDate_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LoadDate_Validate(r);
                }
                private static global::System.DateTime _LoadDate_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.LoadDate;
                }
                private static void _LoadDate_SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.LoadDate = global::LightSwitchApplication.ClientRole.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _LoadDate_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.LoadDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry
                    ClientRoleCode = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry(
                        "ClientRoleCode",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleCode_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleCode_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleCode_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleCode_GetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleCode_SetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ClientRoleCode_OnValueChanged);
                private static void _ClientRoleCode_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._ClientRoleCode, sf);
                }
                private static bool _ClientRoleCode_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.ClientRoleCode_IsReadOnly(ref result);
                    return result;
                }
                private static void _ClientRoleCode_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ClientRoleCode_Validate(r);
                }
                private static string _ClientRoleCode_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.ClientRoleCode;
                }
                private static void _ClientRoleCode_SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ClientRoleCode = v;
                }
                private static void _ClientRoleCode_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.ClientRoleCode_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.Nullable<int>>.Entry
                    LoadDateID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.Nullable<int>>.Entry(
                        "LoadDateID",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDateID_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDateID_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDateID_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDateID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._LoadDateID_OnValueChanged);
                private static void _LoadDateID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._LoadDateID, sf);
                }
                private static bool _LoadDateID_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.LoadDateID_IsReadOnly(ref result);
                    return result;
                }
                private static void _LoadDateID_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LoadDateID_Validate(r);
                }
                private static global::System.Nullable<int> _LoadDateID_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.LoadDateID;
                }
                private static void _LoadDateID_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.LoadDateID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Entry
                    sys_CreatedOn = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Entry(
                        "sys_CreatedOn",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedOn_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedOn_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedOn_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedOn_GetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedOn_SetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedOn_OnValueChanged);
                private static void _sys_CreatedOn_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._sys_CreatedOn, sf);
                }
                private static bool _sys_CreatedOn_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.sys_CreatedOn_IsReadOnly(ref result);
                    return result;
                }
                private static void _sys_CreatedOn_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sys_CreatedOn_Validate(r);
                }
                private static global::System.DateTime _sys_CreatedOn_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.sys_CreatedOn;
                }
                private static void _sys_CreatedOn_SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.sys_CreatedOn = global::LightSwitchApplication.ClientRole.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _sys_CreatedOn_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.sys_CreatedOn_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry
                    sys_CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry(
                        "sys_CreatedBy",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedBy_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedBy_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_CreatedBy_OnValueChanged);
                private static void _sys_CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._sys_CreatedBy, sf);
                }
                private static bool _sys_CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.sys_CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _sys_CreatedBy_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sys_CreatedBy_Validate(r);
                }
                private static string _sys_CreatedBy_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.sys_CreatedBy;
                }
                private static void _sys_CreatedBy_SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d, string v)
                {
                    d.ImplementationEntity.sys_CreatedBy = v;
                }
                private static void _sys_CreatedBy_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.sys_CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Entry
                    sys_ModifiedOn = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Entry(
                        "sys_ModifiedOn",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedOn_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedOn_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedOn_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedOn_GetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedOn_SetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedOn_OnValueChanged);
                private static void _sys_ModifiedOn_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._sys_ModifiedOn, sf);
                }
                private static bool _sys_ModifiedOn_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.sys_ModifiedOn_IsReadOnly(ref result);
                    return result;
                }
                private static void _sys_ModifiedOn_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sys_ModifiedOn_Validate(r);
                }
                private static global::System.DateTime _sys_ModifiedOn_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.sys_ModifiedOn;
                }
                private static void _sys_ModifiedOn_SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.sys_ModifiedOn = global::LightSwitchApplication.ClientRole.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _sys_ModifiedOn_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.sys_ModifiedOn_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry
                    sys_ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Entry(
                        "sys_ModifiedBy",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedBy_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedBy_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedBy_GetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedBy_SetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._sys_ModifiedBy_OnValueChanged);
                private static void _sys_ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._sys_ModifiedBy, sf);
                }
                private static bool _sys_ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.sys_ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _sys_ModifiedBy_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.sys_ModifiedBy_Validate(r);
                }
                private static string _sys_ModifiedBy_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.sys_ModifiedBy;
                }
                private static void _sys_ModifiedBy_SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d, string v)
                {
                    d.ImplementationEntity.sys_ModifiedBy = v;
                }
                private static void _sys_ModifiedBy_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.sys_ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.BillingDetail>.Entry
                    BillingDetails = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.BillingDetail>.Entry(
                        "BillingDetails",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._BillingDetails_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._BillingDetails_GetReferencedEntities,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._BillingDetails_GetEntityCollection);
                private static void _BillingDetails_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.BillingDetail>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._BillingDetails, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.BillingDetail> _BillingDetails_GetReferencedEntities(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.BillingDetail, global::LightSwitchApplication.BillingDetail.DetailsClass>(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.BillingDetails, ref d._BillingDetails);
                }
                private static global::System.Collections.IEnumerable _BillingDetails_GetEntityCollection(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.BillingDetails;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.ActiveType>.Entry
                    ActiveType = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.ActiveType>.Entry(
                        "ActiveType",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ActiveType_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ActiveType_ComputeIsReadOnly,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ActiveType_Validate,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ActiveType_GetCoreImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ActiveType_GetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ActiveType_SetImplementationValue,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ActiveType_Refresh,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._ActiveType_OnValueChanged);
                private static void _ActiveType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.ActiveType>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._ActiveType, sf);
                }
                private static bool _ActiveType_ComputeIsReadOnly(global::LightSwitchApplication.ClientRole e)
                {
                    bool result = false;
                    e.ActiveType_IsReadOnly(ref result);
                    return result;
                }
                private static void _ActiveType_Validate(global::LightSwitchApplication.ClientRole e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ActiveType_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ActiveType_GetCoreImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.ActiveType;
                }
                private static global::LightSwitchApplication.ActiveType _ActiveType_GetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.ActiveType, global::LightSwitchApplication.ActiveType.DetailsClass>(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ActiveType, ref d._ActiveType);
                }
                private static void _ActiveType_SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass d, global::LightSwitchApplication.ActiveType v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ActiveType, ref d._ActiveType, (i, ev) => i.ActiveType = ev, v);
                }
                private static void _ActiveType_Refresh(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.ActiveType, ref d._ActiveType);
                }
                private static void _ActiveType_OnValueChanged(global::LightSwitchApplication.ClientRole e)
                {
                    e.ActiveType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.InvoiceLine>.Entry
                    InvoiceLines = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.InvoiceLine>.Entry(
                        "InvoiceLines",
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._InvoiceLines_Stub,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._InvoiceLines_GetReferencedEntities,
                        global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties._InvoiceLines_GetEntityCollection);
                private static void _InvoiceLines_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ClientRole.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.InvoiceLine>.Data> c, global::LightSwitchApplication.ClientRole.DetailsClass d, object sf)
                {
                    c(d, ref d._InvoiceLines, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.InvoiceLine> _InvoiceLines_GetReferencedEntities(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.InvoiceLine, global::LightSwitchApplication.InvoiceLine.DetailsClass>(global::LightSwitchApplication.ClientRole.DetailsClass.PropertySetProperties.InvoiceLines, ref d._InvoiceLines);
                }
                private static global::System.Collections.IEnumerable _InvoiceLines_GetEntityCollection(global::LightSwitchApplication.ClientRole.DetailsClass d)
                {
                    return d.ImplementationEntity.InvoiceLines;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data _ClientRoleName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, int>.Data _ClientRoleID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data _ClientRoleSourceKey;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Data _LoadDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data _ClientRoleCode;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.Nullable<int>>.Data _LoadDateID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Data _sys_CreatedOn;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data _sys_CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::System.DateTime>.Data _sys_ModifiedOn;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, string>.Data _sys_ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.BillingDetail>.Data _BillingDetails;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.ActiveType>.Data _ActiveType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ClientRole, global::LightSwitchApplication.ClientRole.DetailsClass, global::LightSwitchApplication.InvoiceLine>.Data _InvoiceLines;
            
        }
    
        #endregion
    }
    
    #endregion
}
