

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class TimesheetHour : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the TimesheetHour entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TimesheetHour()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public TimesheetHour(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TimesheetHour> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.TimesheetHour.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TimesheetHour_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TimesheetHour_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Name
        {
            get
            {
                return global::LightSwitchApplication.TimesheetHour.DetailsClass.GetValue(this, global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.Name);
            }
            set
            {
                global::LightSwitchApplication.TimesheetHour.DetailsClass.SetValue(this, global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.Name, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Name_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<decimal> Value
        {
            get
            {
                return global::LightSwitchApplication.TimesheetHour.DetailsClass.GetValue(this, global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.Value);
            }
            set
            {
                global::LightSwitchApplication.TimesheetHour.DetailsClass.SetValue(this, global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.Value, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Value_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Value_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Value_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime c_Date
        {
            get
            {
                return global::LightSwitchApplication.TimesheetHour.DetailsClass.GetValue(this, global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.c_Date);
            }
            set
            {
                global::LightSwitchApplication.TimesheetHour.DetailsClass.SetValue(this, global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.c_Date, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void c_Date_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.TimesheetHour,
                global::LightSwitchApplication.TimesheetHour.DetailsClass,
                global::LightSwitchApplication.TimesheetHour.DetailsClass.IImplementation,
                global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.Name;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass>.Entry
                __TimesheetHourEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass>.Entry(
                    global::LightSwitchApplication.TimesheetHour.DetailsClass.__TimesheetHour_CreateNew,
                    global::LightSwitchApplication.TimesheetHour.DetailsClass.__TimesheetHour_Created,
                    global::LightSwitchApplication.TimesheetHour.DetailsClass.__TimesheetHour_AllowSaveWithErrors);
            private static global::LightSwitchApplication.TimesheetHour __TimesheetHour_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.TimesheetHour> es)
            {
                return new global::LightSwitchApplication.TimesheetHour(es);
            }
            private static void __TimesheetHour_Created(global::LightSwitchApplication.TimesheetHour e)
            {
                e.TimesheetHour_Created();
            }
            private static bool __TimesheetHour_AllowSaveWithErrors(global::LightSwitchApplication.TimesheetHour e)
            {
                bool result = false;
                e.TimesheetHour_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, string> Name
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.Name) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.Nullable<decimal>> Value
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.Value) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.Nullable<decimal>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.DateTime> c_Date
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties.c_Date) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.DateTime>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string Name { get; set; }
                new global::System.Nullable<decimal> Value { get; set; }
                new global::System.DateTime c_Date { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, string>.Entry
                    Name = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, string>.Entry(
                        "Name",
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Name_Stub,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Name_ComputeIsReadOnly,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Name_Validate,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Name_GetImplementationValue,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Name_SetImplementationValue,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Name_OnValueChanged);
                private static void _Name_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TimesheetHour.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, string>.Data> c, global::LightSwitchApplication.TimesheetHour.DetailsClass d, object sf)
                {
                    c(d, ref d._Name, sf);
                }
                private static bool _Name_ComputeIsReadOnly(global::LightSwitchApplication.TimesheetHour e)
                {
                    bool result = false;
                    e.Name_IsReadOnly(ref result);
                    return result;
                }
                private static void _Name_Validate(global::LightSwitchApplication.TimesheetHour e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Name_Validate(r);
                }
                private static string _Name_GetImplementationValue(global::LightSwitchApplication.TimesheetHour.DetailsClass d)
                {
                    return d.ImplementationEntity.Name;
                }
                private static void _Name_SetImplementationValue(global::LightSwitchApplication.TimesheetHour.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Name = v;
                }
                private static void _Name_OnValueChanged(global::LightSwitchApplication.TimesheetHour e)
                {
                    e.Name_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.Nullable<decimal>>.Entry
                    Value = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.Nullable<decimal>>.Entry(
                        "Value",
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Value_Stub,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Value_ComputeIsReadOnly,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Value_Validate,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Value_GetImplementationValue,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Value_SetImplementationValue,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._Value_OnValueChanged);
                private static void _Value_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TimesheetHour.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.Nullable<decimal>>.Data> c, global::LightSwitchApplication.TimesheetHour.DetailsClass d, object sf)
                {
                    c(d, ref d._Value, sf);
                }
                private static bool _Value_ComputeIsReadOnly(global::LightSwitchApplication.TimesheetHour e)
                {
                    bool result = false;
                    e.Value_IsReadOnly(ref result);
                    return result;
                }
                private static void _Value_Validate(global::LightSwitchApplication.TimesheetHour e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Value_Validate(r);
                }
                private static global::System.Nullable<decimal> _Value_GetImplementationValue(global::LightSwitchApplication.TimesheetHour.DetailsClass d)
                {
                    return d.ImplementationEntity.Value;
                }
                private static void _Value_SetImplementationValue(global::LightSwitchApplication.TimesheetHour.DetailsClass d, global::System.Nullable<decimal> v)
                {
                    d.ImplementationEntity.Value = v;
                }
                private static void _Value_OnValueChanged(global::LightSwitchApplication.TimesheetHour e)
                {
                    e.Value_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.DateTime>.Entry
                    c_Date = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.DateTime>.Entry(
                        "c_Date",
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._c_Date_Stub,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._c_Date_ComputeIsReadOnly,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._c_Date_Validate,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._c_Date_GetImplementationValue,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._c_Date_SetImplementationValue,
                        global::LightSwitchApplication.TimesheetHour.DetailsClass.PropertySetProperties._c_Date_OnValueChanged);
                private static void _c_Date_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.TimesheetHour.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.TimesheetHour.DetailsClass d, object sf)
                {
                    c(d, ref d._c_Date, sf);
                }
                private static bool _c_Date_ComputeIsReadOnly(global::LightSwitchApplication.TimesheetHour e)
                {
                    bool result = false;
                    e.c_Date_IsReadOnly(ref result);
                    return result;
                }
                private static void _c_Date_Validate(global::LightSwitchApplication.TimesheetHour e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.c_Date_Validate(r);
                }
                private static global::System.DateTime _c_Date_GetImplementationValue(global::LightSwitchApplication.TimesheetHour.DetailsClass d)
                {
                    return d.ImplementationEntity.c_Date;
                }
                private static void _c_Date_SetImplementationValue(global::LightSwitchApplication.TimesheetHour.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.c_Date = global::LightSwitchApplication.TimesheetHour.DetailsClass.TruncateDate(v);
                }
                private static void _c_Date_OnValueChanged(global::LightSwitchApplication.TimesheetHour e)
                {
                    e.c_Date_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, string>.Data _Name;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.Nullable<decimal>>.Data _Value;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.TimesheetHour, global::LightSwitchApplication.TimesheetHour.DetailsClass, global::System.DateTime>.Data _c_Date;
            
        }
    
        #endregion
    }
    
    #endregion
}
