// Warning: AutoGenerated file, Don't edit.
document.writeln("<script type=\"text/javascript\" src=\"UserCode/BrowseSalesOrderHeaders.js\"></script>");
document.writeln("<script type=\"text/javascript\" src=\"UserCode/ViewSalesOrderDetail.js\"></script>");
